# Generated by Django 3.1.3 on 2020-11-30 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=35)),
                ('precio', models.FloatField()),
                ('esLente', models.BooleanField(default='False')),
                ('distaciaLente', models.CharField(choices=[('LJ', 'Lejos'), ('CE', 'Cerca')], default='', max_length=2)),
                ('tipoFocal', models.CharField(choices=[('IZ', 'Izuquierda'), ('DE', 'Derecha')], default='', max_length=2)),
                ('tieneArmazon', models.BooleanField(default='False')),
                ('id_Pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedido.pedido')),
            ],
        ),
    ]
