# Generated by Django 3.1.3 on 2020-11-30 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalMedico',
            fields=[
                ('id_PersonalMedico', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=35)),
                ('apellido', models.CharField(default='', max_length=45)),
                ('legajo_empleado', models.CharField(max_length=10)),
                ('id_pacienteAsignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paciente.paciente')),
            ],
        ),
    ]
