# Generated by Django 3.1.3 on 2020-11-30 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PersonalMedico', '0001_initial'),
        ('Paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonalMedico.personalmedico')),
                ('tomado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paciente.paciente')),
            ],
        ),
    ]
