# Generated by Django 3.1.3 on 2020-11-30 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0001_initial'),
        ('Pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='id_Paciente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Paciente.paciente'),
            preserve_default=False,
        ),
    ]
