# Generated by Django 3.1.3 on 2020-11-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0002_pedido_id_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estadoPedido',
            field=models.CharField(choices=[('FI', 'Finalizado'), ('PR', 'Procesando')], default='PR', max_length=2),
        ),
    ]
