# Generated by Django 3.1.3 on 2020-11-30 01:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=35)),
                ('apellido', models.CharField(default='', max_length=45)),
                ('dni', models.CharField(default='', max_length=10)),
                ('registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('horario', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
