# Generated by Django 3.1.3 on 2020-11-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_Pedido', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('id_Producto', models.IntegerField()),
                ('cantidad_Prod', models.IntegerField()),
                ('subTotal', models.FloatField()),
                ('total', models.FloatField()),
                ('tipoPago', models.CharField(choices=[('TC', 'Tarjeta de Credito'), ('DE', 'Tarjeta de Debito'), ('BV', 'Billetera Virtual'), ('EF', 'Efectivo')], default='EF', max_length=2)),
            ],
        ),
    ]
