# Generated by Django 3.1.3 on 2020-11-30 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_Clinico',
            fields=[
                ('id_Historial', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('fechaObservacion', models.DateTimeField()),
                ('observacion', models.TextField(max_length=200)),
                ('id_Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paciente.paciente')),
            ],
        ),
    ]
